### ISSUE TITLE
...

### ISSUE THREAD

**Issue by dimdenGD** [SuperOP535/superop535.github.io#1]
Sorry that i'm writing to you here, but I don't know any other ways to contact you.

First off, the OWOP is HTTPS now, so I can't connect to the WebChat now from OWOP, can you update it please? Thanks.
Secondly, why did you got banned from Discord?

Waiting for your reply!

**Comment by SuperOP535** [comment]
hi, it's okay. i fixed the origin checking and now it allows https:// (no http:// anymore, i checked and it redirects to https anyways so that's not a problem)
